# fly.toml app configuration file generated for chat-project-red-waterfall-3034 on 2026-02-17T00:15:44+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chat-project-red-waterfall-3034'
primary_region = 'nrt'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  grace_period = "30s"

[[vm]]
  size = 'shared-cpu-1x'
  cpus = 1
  memory_mb = 512

#[[statics]]
# guest_path = '/code/static'
# url_prefix = '/static/'
