# Generated by Django 5.1 on 2026-03-21 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_chatmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sockets',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sockets', to='chat.chatroom'),
        ),
    ]
