# Generated by Django 5.1 on 2026-03-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_notify_room_create_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notify_room_create',
            field=models.BooleanField(default=False, verbose_name='誰かが部屋作成したら通知を受け取る'),
        ),
    ]
